### create user
POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email" : "sempak@gmail.com",
  "password": "123456",
  "username":"sempak"
}


### get user
GET   http://localhost:5000/api/users

### login user
POST    http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username":"sempak",
  "password":"123456"
}


### get all profile
GET   http://localhost:5000/api/profiles

### get profile BY ID
GET   http://localhost:5000/api/profiles/662b53b4cb2facbde95d21ed




### create profile
POST   http://localhost:5000/api/profiles
Content-Type: application/json

 {
   "displayName": "John",
   "gender": "male",
   "birthday": "1993-01-01",
   "height": 180,
   "weight": 75
 }




### create profile
PATCH    http://localhost:5000/api/profiles/662b44bb6a9968727303e590
Content-Type: application/json

 {
   "displayName": "jOHN CENA cimeng",
   "gender": "famale",
   "birthday": "1993-01-03",
   "height": 180,
   "weight": 75
 }





### create message
POST   http://localhost:5000/api/message
Content-Type: application/json

 {
   "sender": "Kaka",
   "recipient": "Balo",
   "message": "xxxxx"
 }